# Generated by Django 6.0.6 on 2026-06-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
